### ISSUE TITLE
Unnecessary "applications" key in manifest

### ISSUE THREAD

**Issue by mart3323** [Madis0/More-HTTPS-2#3]
In the manifest file there's an "applications" key which causes an error on chromium 63, and possibly other browsers as well

According to Mozilla, this key is only necessary for firefox browsers older than firefox 48 [source](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications), which make up around 0.5% of all users [source](https://caniuse.com/usage-table)
Therefore, i suggest dropping the offending key from the manifest

**Comment by Madis0** [comment]
Fixed in #2.
